name: Manual eval trigger

on:
  # Lets you pass inputs to workflows when manually triggering them from the Actions tab
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo "Evaluation manually triggered"
