name: Check PullRequest

on:
  # Triggers the workflow on pull request events but only for the "submit" branch
  pull_request_target:
    branches: ["submit"]

jobs:
  check_PR:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip" # caching pip dependencies
      - run: pip install -r requirements.txt

      - name: Check submission PR
        run: python scripts/check_submission.py
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      #- name: add label to PR
      #  uses: andymckay/labeler@master
      #  with:
      #    add-labels: "automerge"

      # merge PR, if steps have not thrown errors yet
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: if_merged
        if: ${{ steps.automerge.outputs.mergeResult == 'merged'}}
        run: |
          echo "Pull request ${{ steps.automerge.outputs.pullRequestNumber }} merged"
          echo "Forecast successfully submitted. Thank you for your participation!"
      - name: if_not_merged
        # let pipeline fail
        if: ${{ steps.automerge.outputs.mergeResult != 'merged'}}
        run: |
          echo "Pull request could not be merged automatically. Waiting for manual review."
          exit 1
