name: PR merge success

# only runs on manual merge of pull request from fork anymore?!
on:
  pull_request:  # stay on pull_request, not pull_request target
    branches:
      - submit
    types:
      - closed

# only after PR was merged
jobs:
  verify_merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Evaluate new submissions
        run: echo "Submission PR successfully merged"
