name: Evaluate submission

# run on merged pull request or manual start
on:
 workflow_run:
    workflows: [Manual eval trigger, PR merge success, Check PullRequest]
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-a-workflow-based-on-the-conclusion-of-another-workflow
    types:
      - completed

# only after PR was merged
jobs:
  evaluate:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: submit
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      
      # evaluate new submissions, update leaderboard
      - name: Evaluate new submissions
        run: python evaluate.py
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
      # TODO: pull request to main?
      # -> automerge it
