name: Scheduled eval trigger

# Controls when the workflow will run
on:
  schedule:
    - cron: "39 8 * * *" # every morning

jobs:
  trigger:
    if: github.repository_owner == 'rki-daki-fws'
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo "Evaluation triggered on schedule"
